---
title: "Baldeep Dhada"
output: pdf_document
date: "2024-01-24"
---

# Jan 24, 2024:

Created the get_seasons(), format_season_name() functions, and updated the main function to handle a show input that doesn't exist in the API. Instead of printing the results as they are, I decided to print the results as a data frame and requested my team members to also make any future results as a dataframe.

# Jan 25, 2024:

Made an update to format_season_name to handle empty strings and replace it with ?. Updated the main function to make the output more clean. Added a while loop so the user can keep using the program, added breaks within it to exit the program at any level. Added documentation for format_season_name and get_seasons.

# Jan 28, 2024:

Created get_all_episodes, format_all_episodes, generate_season_ratings_plot functions for data analysis. Updated the main function to take in additional user input for analysis of a season or analysis of a show in general.

# Jan 29, 2024:

Added comments to the main function and added documentation to some functions

# Feb 4, 2024:

Created unit tests for get_seasons, format_seasons_name, get all_episodes and format_all_episodes and updated the main function in shows.R. Fixed a bug in the plotting functions to return a string if there are no ratings available.

# Feb 5, 2024:

Updated the code for the graphs. Centered the main title and increased its font size, increased font size for the axis labels and added different colors for the line plots.

# Feb 8, 2024:

Added the license and updated the Read me to fix an issue with the description of the API. Updated email address associated with Git on my local machine to match the one on Github because it wasn't showing the proper number of commits from my side. Pushed the main package.
